[package]
name = "sepo_miner"
version = "0.1.0"
edition = "2024"

[dependencies]
argon2 = "0.5.3"
hex = "0.4.3"
rand = "0.9.2"
serde = "1.0.228"
serde_json = "1.0.149"
tokio = { version = "1.49.0", features = ["full"] }
tungstenite = "0.28.0"
url = "2.5.8"
